spring:
  application:
    name: servicio-instrucciones
    
  #Config file
  servlet:    multipart:      max-file-size: 16MB
      max-request-size: 16MB        
  datasource:
    initialization-mode: always
    url: jdbc:h2:mem:fiduciarioPlus;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=Oracle
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-developers