INSERT INTO INSTRUCCION (TIPO_DE_INSTRUCCION) VALUES('venta de valores y transferencia');
INSERT INTO INSTRUCCION (TIPO_DE_INSTRUCCION, ID_DOCUMENTO, NOMBRE_DOCUMENTO, REQUERIDO,DOCUMENTO_ADICIONAL) VALUES('venta de valores y transferencia2','ANEXO','credencial', 'TRUE',FALSE);
INSERT INTO INSTRUCCION (TIPO_DE_INSTRUCCION) VALUES('venta de valores y transferencia3');
INSERT INTO INSTRUCCION (TIPO_DE_INSTRUCCION, ID_DOCUMENTO, NOMBRE_DOCUMENTO, REQUERIDO,DOCUMENTO_ADICIONAL) VALUES('venta de valores y transferencia 4 ','ANEXO','CURP', 'TRUE',FALSE);
INSERT INTO INSTRUCCION (TIPO_DE_INSTRUCCION) VALUES('venta de valores y transferencia 5');
INSERT INTO INSTRUCCION (TIPO_DE_INSTRUCCION, ID_DOCUMENTO, NOMBRE_DOCUMENTO, REQUERIDO,DOCUMENTO_ADICIONAL) VALUES('venta de valores y transferencia 6','ANEXO','PASAPORTE','TRUE',FALSE);
INSERT INTO INSTRUCCION (TIPO_DE_INSTRUCCION, ID_DOCUMENTO, NOMBRE_DOCUMENTO, REQUERIDO,DOCUMENTO_ADICIONAL) VALUES('venta de valores y transferencia 7','ANEXO','RECIBO DE LUZ','TRUE',FALSE);
INSERT INTO INSTRUCCION (TIPO_DE_INSTRUCCION, ID_DOCUMENTO, NOMBRE_DOCUMENTO, REQUERIDO,DOCUMENTO_ADICIONAL) VALUES('venta de valores y transferencia 8','ANEXO','RECIBO DE NOMINA','TRUE',FALSE);
INSERT INTO INSTRUCCION (TIPO_DE_INSTRUCCION, ID_DOCUMENTO, NOMBRE_DOCUMENTO, REQUERIDO,DOCUMENTO_ADICIONAL) VALUES('venta de valores y transferencia 9','ANEXO','NSS','TRUE',FALSE);